name: Deploy to staging.novonode.com

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VPS
        uses: appleboy/ssh-action@master
        with:
          host: 172.93.100.201
          username: root
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/pterodactyl
            git pull origin staging
            yarn install
            export NODE_OPTIONS=--openssl-legacy-provider # for NodeJS v17+
            yarn run build:production
            php artisan route:clear && php artisan cache:clear && php artisan view:clear
            yes | php artisan migrate
            echo "Updated staging panel to latest"
